global:
  scrape_interval: 30s
  evaluation_interval: 30s

scrape_configs:
  - job_name: supabase_exporter
    metrics_path: /customer/v1/privileged/metrics
    basic_auth:
      username: service_role
      password: __SERVICE_ROLE_KEY__
    static_configs:
      - targets:
        - __PROJECT_REF__.supabase.co
          